-- =========================
-- USERS
-- ===========
-- ==============
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100),
    birthday DATE NOT NULL
);

-- =========================
-- MPA
-- =========================
CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

-- =========================
-- FILMS
-- =========================
CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa_id INTEGER,

    CONSTRAINT fk_films_mpa
        FOREIGN KEY (mpa_id)
        REFERENCES mpa(id)
);

-- =========================
-- GENRES
-- =========================
CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- =========================
-- FILM_GENRES
-- =========================
CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL,
    genre_id INTEGER NOT NULL,

    PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_film_genres_film
        FOREIGN KEY (film_id)
        REFERENCES films(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_film_genres_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres(id)
);

-- =========================
-- LIKES
-- =========================
CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    PRIMARY KEY (film_id, user_id),

    CONSTRAINT fk_likes_film
        FOREIGN KEY (film_id)
        REFERENCES films(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_likes_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- =========================
-- FRIENDS
-- =========================
CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, friend_id),

    CONSTRAINT fk_friends_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_friends_friend
        FOREIGN KEY (friend_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_friends_not_self
        CHECK (user_id <> friend_id)
);

-- =========================
-- INDEXES
-- =========================
CREATE INDEX IF NOT EXISTS idx_films_mpa_id
    ON films(mpa_id);

CREATE INDEX IF NOT EXISTS idx_film_genres_film_id
    ON film_genres(film_id);

CREATE INDEX IF NOT EXISTS idx_film_genres_genre_id
    ON film_genres(genre_id);

CREATE INDEX IF NOT EXISTS idx_likes_film_id
    ON likes(film_id);

CREATE INDEX IF NOT EXISTS idx_likes_user_id
    ON likes(user_id);

CREATE INDEX IF NOT EXISTS idx_friends_user_id
    ON friends(user_id);

CREATE INDEX IF NOT EXISTS idx_friends_friend_id
    ON friends(friend_id);
